In [1]:
import matplotlib.pyplot as plt
import torch
from nnfabrik.builder import get_data, get_trainer

from model import stacked_core_full_gauss_readout
from trainer import standard_trainer

from autoencoder import Autoenc

random_seed = 42

device = "cuda:7"
torch.cuda.set_device(device)

In [2]:
# loading the SENSORIUM+ dataset
filenames = [
    "/srv/user/polina/sensorium/sensorium/notebooks/data/static23343-5-17-GrayImageNet-94c6ff995dac583098847cfecd43e7b6.zip",
    #"/srv/user/polina/sensorium/sensorium/notebooks/data/static21067-10-18-GrayImageNet-94c6ff995dac583098847cfecd43e7b6.zip", 

]
data_key = '23343-5-17'

dataset_fn = "sensorium.datasets.static_loaders"
dataset_config = {
    "paths": filenames,
    "normalize": True,
    "exclude": None,
    "include_behavior": False,
    "include_eye_position": False,
    "batch_size": 128,
    "scale": 0.25,
}

dataloaders = get_data(dataset_fn, dataset_config)

In [3]:
model_config = {
    "pad_input": False,
    "stack": -1,
    "layers": 4,
    "input_kern": 9,
    "gamma_input": 6.3831,
    "gamma_readout": 0.0076,
    "hidden_kern": 7,
    "hidden_channels": 64,
    "depth_separable": True,
    "grid_mean_predictor": {
        "type": "cortex",
        "input_dimensions": 2,
        "hidden_layers": 1,
        "hidden_features": 30,
        "final_tanh": True,
    },
    "init_sigma": 0.1,
    "init_mu_range": 0.3,
    "gauss_type": "full",
    "shifter": False, 
    "autoencoder": None, 
}

model = stacked_core_full_gauss_readout(dataloaders, random_seed, **model_config)

/srv/user/nathanpaul.soeding/private_neuropredictors/neuralpredictors/layers/readouts/base.py:74: UserWarning: Use of 'gamma_readout' is deprecated. Use 'feature_reg_weight' instead. If 'feature_reg_weight' is defined, 'gamma_readout' is ignored
  warnings.warn(
/srv/user/nathanpaul.soeding/private_neuropredictors/neuralpredictors/layers/readouts/base.py:95: UserWarning: Readout is NOT initialized with mean activity but with 0!
  warnings.warn("Readout is NOT initialized with mean activity but with 0!")


In [4]:
trainer_fn = "sensorium.training.standard_trainer"
 
trainer_config = {'max_iter': 200,
                 'verbose': False,
                 'lr_decay_steps': 4,
                 'avg_loss': False,
                 'lr_init': 0.009,
                 'device': device, 
                 }

trainer = get_trainer(trainer_fn=trainer_fn, 
                     trainer_config=trainer_config)

In [5]:
#validation_score, trainer_output, state_dict = trainer(model, dataloaders, seed=42)
validation_score, trainer_output, state_dict = standard_trainer(
    model, 
    dataloaders, 
    seed=42, 
    **trainer_config
)

torch.save(model.state_dict(), 'model_weights.pth')

/user/nathanpaul.soeding/miniconda3/lib/python3.12/site-packages/torch/optim/lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(
Epoch 1: 100%|██████████| 35/35 [00:06<00:00,  5.07it/s]


172789219.5


Epoch 2: 100%|██████████| 35/35 [00:03<00:00, 10.85it/s]


155635670.5


Epoch 3: 100%|██████████| 35/35 [00:03<00:00, 10.76it/s]


153529004.5


Epoch 4: 100%|██████████| 35/35 [00:03<00:00, 11.21it/s]


151401715.5


Epoch 5: 100%|██████████| 35/35 [00:03<00:00, 11.07it/s]


149847507.25


Epoch 6: 100%|██████████| 35/35 [00:03<00:00, 10.78it/s]


148490667.75


Epoch 7: 100%|██████████| 35/35 [00:03<00:00, 10.98it/s]


147230167.5


Epoch 8: 100%|██████████| 35/35 [00:03<00:00, 10.84it/s]


145764068.25


Epoch 9: 100%|██████████| 35/35 [00:03<00:00, 11.00it/s]


144618355.75


Epoch 10: 100%|██████████| 35/35 [00:03<00:00, 11.04it/s]


143779993.0


Epoch 11: 100%|██████████| 35/35 [00:03<00:00, 10.76it/s]


143181241.5


Epoch 12: 100%|██████████| 35/35 [00:03<00:00, 10.88it/s]


142539108.75


Epoch 13: 100%|██████████| 35/35 [00:03<00:00, 10.86it/s]


141500324.25


Epoch 14: 100%|██████████| 35/35 [00:03<00:00, 10.55it/s]


141109259.75


Epoch 15: 100%|██████████| 35/35 [00:03<00:00, 10.94it/s]


140442787.5


Epoch 16: 100%|██████████| 35/35 [00:03<00:00,  9.44it/s]


139907643.5


Epoch 17: 100%|██████████| 35/35 [00:03<00:00, 10.30it/s]


139364915.75


Epoch 18: 100%|██████████| 35/35 [00:03<00:00, 10.14it/s]


138999596.0


Epoch 19: 100%|██████████| 35/35 [00:03<00:00, 10.35it/s]


138645623.0


Epoch 20: 100%|██████████| 35/35 [00:03<00:00, 10.41it/s]


138176502.5


Epoch 21: 100%|██████████| 35/35 [00:03<00:00, 11.02it/s]


137798698.25


Epoch 22: 100%|██████████| 35/35 [00:03<00:00, 10.72it/s]


137436969.25


Epoch 23: 100%|██████████| 35/35 [00:03<00:00, 10.89it/s]


136845735.5


Epoch 24: 100%|██████████| 35/35 [00:03<00:00,  9.55it/s]


136715407.0


Epoch 25: 100%|██████████| 35/35 [00:03<00:00, 10.88it/s]


136393505.0


Epoch 26: 100%|██████████| 35/35 [00:03<00:00, 10.83it/s]


136504988.25


Epoch 27: 100%|██████████| 35/35 [00:03<00:00, 10.63it/s]


135912833.75


Epoch 28: 100%|██████████| 35/35 [00:03<00:00, 10.82it/s]


135551928.25


Epoch 29: 100%|██████████| 35/35 [00:03<00:00, 10.70it/s]


135428446.75


Epoch 30: 100%|██████████| 35/35 [00:03<00:00, 11.20it/s]


135165096.75


Epoch 31: 100%|██████████| 35/35 [00:03<00:00, 10.66it/s]


134926445.0


Epoch 32: 100%|██████████| 35/35 [00:03<00:00, 10.67it/s]


134739917.75


Epoch 33: 100%|██████████| 35/35 [00:03<00:00, 10.67it/s]


134642884.25


Epoch 34: 100%|██████████| 35/35 [00:03<00:00, 10.78it/s]


134372025.5


Epoch 35: 100%|██████████| 35/35 [00:03<00:00, 10.99it/s]


134207580.25


Epoch 36: 100%|██████████| 35/35 [00:03<00:00, 11.14it/s]


134284341.0


Epoch 37: 100%|██████████| 35/35 [00:03<00:00, 10.89it/s]


134039872.25


Epoch 38: 100%|██████████| 35/35 [00:03<00:00, 10.83it/s]


133772137.5


Epoch 39: 100%|██████████| 35/35 [00:03<00:00, 11.06it/s]


133648345.5


Epoch 40: 100%|██████████| 35/35 [00:03<00:00, 10.87it/s]


134285556.5


Epoch 41: 100%|██████████| 35/35 [00:03<00:00, 11.24it/s]


132327422.0


Epoch 42: 100%|██████████| 35/35 [00:03<00:00, 10.51it/s]


131389149.25


Epoch 43: 100%|██████████| 35/35 [00:03<00:00, 11.26it/s]


131200749.25


Epoch 44: 100%|██████████| 35/35 [00:03<00:00, 10.71it/s]


131082609.75


Epoch 45: 100%|██████████| 35/35 [00:03<00:00, 11.11it/s]


130927233.5


Epoch 46: 100%|██████████| 35/35 [00:03<00:00, 10.47it/s]


130897998.5


Epoch 47: 100%|██████████| 35/35 [00:03<00:00, 10.92it/s]


130859576.75


Epoch 48: 100%|██████████| 35/35 [00:03<00:00, 10.79it/s]


130932837.75


Epoch 49: 100%|██████████| 35/35 [00:03<00:00, 10.88it/s]


130720047.5


Epoch 50: 100%|██████████| 35/35 [00:03<00:00, 10.98it/s]


130592432.0


Epoch 51: 100%|██████████| 35/35 [00:03<00:00, 11.12it/s]


130919423.75


Epoch 52: 100%|██████████| 35/35 [00:03<00:00, 10.95it/s]


130196276.5


Epoch 53: 100%|██████████| 35/35 [00:03<00:00, 10.86it/s]


130020980.5


Epoch 54: 100%|██████████| 35/35 [00:03<00:00, 11.11it/s]


129915555.75


Epoch 55: 100%|██████████| 35/35 [00:03<00:00, 10.95it/s]


129890722.75


Epoch 56: 100%|██████████| 35/35 [00:03<00:00, 10.86it/s]


130250260.25


Epoch 57: 100%|██████████| 35/35 [00:03<00:00, 10.67it/s]


130065602.0


Epoch 58: 100%|██████████| 35/35 [00:03<00:00, 10.50it/s]


129799123.0


Epoch 59: 100%|██████████| 35/35 [00:03<00:00, 10.76it/s]


129749733.0


Epoch 60: 100%|██████████| 35/35 [00:03<00:00, 11.09it/s]


129736324.75


In [7]:
validation_score

np.float32(0.32743725)

In [ ]:
model.load_state_dict(torch.load('model_weights.pth'))

<All keys matched successfully>

In [8]:
checkpoint = torch.load('model_weights.pth')
features = checkpoint['readout.23343-5-17._features']
features = features.squeeze().permute(1, 0).detach()

In [ ]:
hidden_dims = 512
hidden_layers = 0
hidden_dims = [hidden_dims] * hidden_layers
autoencoder = Autoenc(64, 64, hidden_dims, batch_norm=True)
autoencoder.to(device) 

Autoenc(
  (encoder): Sequential(
    (0): Linear(in_features=64, out_features=64, bias=True)
  )
  (decoder): Sequential(
    (0): Linear(in_features=64, out_features=64, bias=True)
  )
)

In [10]:
criterion = torch.nn.MSELoss(reduction='sum')
optim = torch.optim.Adam(autoencoder.parameters(), lr=1e-3)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optim, factor=0.3, patience=25)

In [11]:
epochs = 100000
min_lr = 1e-5

for epoch in range(epochs):
    recon = autoencoder(features)
    loss = criterion(features, recon)

    optim.zero_grad()
    loss.backward()
    optim.step()
    scheduler.step(loss.item())
    if epoch % 100 == 0:
        lr = optim.param_groups[0]['lr']
        if lr < min_lr:
            break

        print(lr, loss.item())

0.001 22305.484375
0.001 4871.291015625
0.001 1344.253173828125
0.001 499.34161376953125
0.001 219.47991943359375
0.001 99.18595886230469
0.001 52.83953857421875
0.001 39.393524169921875
0.001 24.54690170288086
0.001 5.0771684646606445
0.001 0.24569296836853027
0.001 0.0069335829466581345
0.001 0.00016939286433625966
0.001 3.926505087292753e-06
0.001 1.0655733007070012e-07
0.001 9.874813855503817e-09
0.001 5.100092792531541e-09
0.001 4.270321873889316e-09
0.001 3.902651535270252e-09
0.001 3.595624464836078e-09
0.001 3.3321141401643217e-09
0.001 3.0781315274452936e-09
0.001 2.8373410287940715e-09
0.001 2.639397367332208e-09
0.001 2.4486150884683866e-09
0.001 2.2898056784015353e-09
0.001 2.1358963486761695e-09
0.001 1.9948751539544674e-09
0.001 1.8640116117296657e-09
0.001 1.7596216705939582e-09
0.001 1.6591255036502162e-09
0.001 1.5753655047134885e-09
0.001 1.4960139793629423e-09
0.001 1.4355071575877787e-09
0.001 1.3708839619042124e-09
0.001 1.313528952273657e-09
0.001 1.26462640359648

In [12]:
autoencoder(features), features

(tensor([[ 0.0708, -0.1934,  0.1159,  ..., -0.2027, -0.1143, -0.0392],
         [ 0.1427, -0.2534,  0.1852,  ..., -0.3230, -0.1466, -0.0762],
         [-0.2591,  0.0429,  0.0367,  ..., -0.2654, -0.2255,  0.2281],
         ...,
         [-0.0264, -0.0735, -0.3096,  ..., -0.2099, -0.0353, -0.2916],
         [-0.1548, -0.1368,  0.1351,  ..., -0.0858, -0.1118,  0.0107],
         [ 0.1195,  0.5379, -0.2256,  ..., -0.0869,  0.1990, -0.0797]],
        device='cuda:7', grad_fn=<AddmmBackward0>),
 tensor([[ 0.0708, -0.1934,  0.1159,  ..., -0.2027, -0.1143, -0.0392],
         [ 0.1427, -0.2534,  0.1852,  ..., -0.3230, -0.1466, -0.0762],
         [-0.2591,  0.0429,  0.0367,  ..., -0.2654, -0.2255,  0.2281],
         ...,
         [-0.0264, -0.0735, -0.3096,  ..., -0.2099, -0.0353, -0.2916],
         [-0.1548, -0.1368,  0.1351,  ..., -0.0858, -0.1118,  0.0107],
         [ 0.1195,  0.5379, -0.2256,  ..., -0.0869,  0.1990, -0.0797]],
        device='cuda:7'))

In [6]:
#autoencoder = VAE(64, 16, [32, 32], batch_norm=False, dropout=0., nonlinearity='GELU')
#model_config['autoencoder'] = None
model_autoenc = stacked_core_full_gauss_readout(dataloaders, random_seed, **model_config)

In [8]:
# select all parameters that are not autoencoder
params = [(name, param) for name, param in model_autoenc.named_parameters() if 'autoencoder' not in name]
freeze_params = ['core', 'readout']


# copy parameters and freeze them
for (name, param_autoenc), param_base in zip(params, model.parameters()):
    param_autoenc.data.copy_(param_base.data)

    param_autoenc.requires_grad = not any(word in name for word in freeze_params)

In [9]:
#[(name, param.shape, param.requires_grad) for name, param in model_autoenc.named_parameters()]

In [10]:
for p1, p2 in zip(model.parameters(), model_autoenc.parameters()):
    print(torch.all(p1 == p2))

tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)
tensor(True)


In [ ]:
core_lr = 1e-10
autoencoder_lr = 1e-10
readout_lr = 1e-5
shifter_lr = 1e-5


optimizer = torch.optim.Adam([
    #{'params': model_autoenc.core.parameters(), 'lr': core_lr}, 
    {'params': model_autoenc.readout[data_key].autoencoder.parameters(), 'lr': autoencoder_lr},
    #{'params': model_autoenc.readout[data_key].sigma, 'lr': readout_lr},
    #{'params': model_autoenc.readout[data_key]._features, 'lr': readout_lr},
    #{'params': model_autoenc.readout[data_key].bias, 'lr': readout_lr},
    #{'params': model_autoenc.readout[data_key].mu_transform.parameters(), 'lr': readout_lr},
    #{'params': model_autoenc.shifter.parameters(), 'lr': shifter_lr},
])

trainer_config = {
    'max_iter': 0,
    'verbose': False,
    'lr_decay_steps': 4,
    'avg_loss': False,
    'lr_init': 0.009,
    'device': device, 
    'optimizer': optimizer, 
}

validation_score, trainer_output, state_dict = standard_trainer(
    model_autoenc, 
    dataloaders, 
    seed=42, 
    **trainer_config
)

/user/nathanpaul.soeding/miniconda3/lib/python3.12/site-packages/torch/optim/lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(


In [27]:
validation_score

np.float32(0.018295547)

In [ ]:
batch = next(iter(dataloaders["validation"][data_key]))
imgs, responses = batch

In [ ]:
model.to(device);
model(imgs)

tensor([[0.4580, 0.7329, 0.3655,  ..., 0.5830, 0.4406, 0.4084],
        [0.1065, 0.0691, 0.0861,  ..., 0.0832, 0.1880, 0.0298],
        [0.2401, 0.3604, 0.1206,  ..., 0.6898, 0.5531, 0.8214],
        ...,
        [0.6314, 1.2438, 0.8060,  ..., 0.4730, 0.8891, 0.1635],
        [0.6516, 1.4335, 1.3495,  ..., 0.4134, 0.7115, 1.3980],
        [0.2650, 0.3758, 0.1441,  ..., 0.1647, 0.4374, 0.5120]],
       device='cuda:7', grad_fn=<AddBackward0>)

In [ ]:
model_autoenc.to(device);
model_autoenc(imgs)

tensor([[0.4966, 0.8408, 0.3649,  ..., 0.6131, 0.4797, 0.4172],
        [0.0894, 0.0519, 0.0669,  ..., 0.0638, 0.1793, 0.0209],
        [0.2177, 0.3510, 0.0897,  ..., 0.7401, 0.5880, 0.8916],
        ...,
        [0.5775, 1.3487, 0.8308,  ..., 0.5007, 0.8611, 0.1449],
        [0.6545, 1.5715, 1.5258,  ..., 0.4712, 0.7711, 1.4438],
        [0.2582, 0.3742, 0.1251,  ..., 0.1559, 0.4563, 0.5553]],
       device='cuda:7')

In [18]:
from sensorium.utility.scores import get_correlations

model.eval()

# Compute avg validation and test correlation
validation_correlation = get_correlations(
    model, dataloaders["validation"], device=device, as_dict=False, per_neuron=False
)

print(validation_correlation)

model_autoenc.eval()

# Compute avg validation and test correlation
validation_correlation = get_correlations(
    model_autoenc, dataloaders["validation"], device=device, as_dict=False, per_neuron=False 
)

print(validation_correlation)

0.32872394
0.32494497


In [8]:
model_autoenc.load_state_dict(torch.load('model_autoenc_weights.pth'))

RuntimeError: Error(s) in loading state_dict for FiringRateEncoder:
	Missing key(s) in state_dict: "shifter.23343-5-17.mlp.0.weight", "shifter.23343-5-17.mlp.0.bias", "shifter.23343-5-17.mlp.2.weight", "shifter.23343-5-17.mlp.2.bias", "shifter.23343-5-17.mlp.4.weight", "shifter.23343-5-17.mlp.4.bias". 
	size mismatch for core.features.layer0.conv.weight: copying a param with shape torch.Size([64, 1, 9, 9]) from checkpoint, the shape in current model is torch.Size([64, 4, 9, 9]).